/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: CredentialsWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CredentialsWithRelations {
  email: string;
  password: string;
}
