/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransThanhKhoanFilter1FieldsOneOf } from './khovtTransThanhKhoanFilter1FieldsOneOf';
import type { KhovtTransThanhKhoanFilter1FieldsOneOfTwoItem } from './khovtTransThanhKhoanFilter1FieldsOneOfTwoItem';

export type KhovtTransThanhKhoanFilter1Fields =
  | KhovtTransThanhKhoanFilter1FieldsOneOf
  | KhovtTransThanhKhoanFilter1FieldsOneOfTwoItem[];
