/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransPhieuXuatFilterFieldsOneOf = {
  diDoXuat?: boolean;
  ghiChu?: boolean;
  id?: boolean;
  khoNhap?: boolean;
  khoXuat?: boolean;
  ngayXuat?: boolean;
  nguoiTaoPhieu?: boolean;
  soPhieu?: boolean;
  status?: boolean;
  thongTinCanhBao?: boolean;
};
