/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterNhomFilter1FieldsOneOfTwoItem =
  (typeof KhovtMasterNhomFilter1FieldsOneOfTwoItem)[keyof typeof KhovtMasterNhomFilter1FieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterNhomFilter1FieldsOneOfTwoItem = {
  ghiChu: 'ghiChu',
  id: 'id',
  maNhom: 'maNhom',
  tenNhom: 'tenNhom',
} as const;
