/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Partial<KhovtTransPhieuNhap>, schemaOptions: { partial: true })
 */
export interface KhovtTransPhieuNhapPartial {
  /** @nullable */
  donViNhap?: string | null;
  /** @nullable */
  ghiChu?: string | null;
  /** */
  id?: number;
  /** @nullable */
  maKho?: string | null;
  /** @nullable */
  ngayNhanKqtn?: string | null;
  /** @nullable */
  ngayNhap?: string | null;
  /** @nullable */
  nguoiNhap?: string | null;
  /** @nullable */
  soHoaDon?: string | null;
  /** @nullable */
  soPhieuNhap?: string | null;
  /** @nullable */
  typeNhap?: string | null;
  /** @nullable */
  viTriLuuKho?: string | null;
  /** @nullable */
  xeVanChuyen?: string | null;
}
