/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransThanhKhoanFilterFields } from './khovtTransThanhKhoanFilterFields';
import type { KhovtTransThanhKhoanFilterOrder } from './khovtTransThanhKhoanFilterOrder';

export interface KhovtTransThanhKhoanFilter {
  fields?: KhovtTransThanhKhoanFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtTransThanhKhoanFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
