/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterKhoFilterFields } from './khovtMasterKhoFilterFields';
import type { KhovtMasterKhoFilterOrder } from './khovtMasterKhoFilterOrder';

export interface KhovtMasterKhoFilter {
  fields?: KhovtMasterKhoFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterKhoFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
