/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNguonGocFilterFieldsOneOf } from './khovtMasterNguonGocFilterFieldsOneOf';
import type { KhovtMasterNguonGocFilterFieldsOneOfTwoItem } from './khovtMasterNguonGocFilterFieldsOneOfTwoItem';

export type KhovtMasterNguonGocFilterFields =
  | KhovtMasterNguonGocFilterFieldsOneOf
  | KhovtMasterNguonGocFilterFieldsOneOfTwoItem[];
