/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNguonGocFilterFields } from './khovtMasterNguonGocFilterFields';
import type { KhovtMasterNguonGocFilterOrder } from './khovtMasterNguonGocFilterOrder';

export interface KhovtMasterNguonGocFilter {
  fields?: KhovtMasterNguonGocFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterNguonGocFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
