/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterVtFilter } from './khovtMasterVtFilter';

export type KhovtMasterVtControllerFindByIdParams = {
  filter?: KhovtMasterVtFilter;
};
