/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterVtFilter1FieldsOneOf } from './khovtMasterVtFilter1FieldsOneOf';
import type { KhovtMasterVtFilter1FieldsOneOfTwoItem } from './khovtMasterVtFilter1FieldsOneOfTwoItem';

export type KhovtMasterVtFilter1Fields = KhovtMasterVtFilter1FieldsOneOf | KhovtMasterVtFilter1FieldsOneOfTwoItem[];
