/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterVtFilter1FieldsOneOfTwoItem =
  (typeof KhovtMasterVtFilter1FieldsOneOfTwoItem)[keyof typeof KhovtMasterVtFilter1FieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterVtFilter1FieldsOneOfTwoItem = {
  dvt: 'dvt',
  ghiChu: 'ghiChu',
  maNhom: 'maNhom',
  maVt: 'maVt',
  tenVt: 'tenVt',
} as const;
