/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Partial<KhovtMasterNhom>, schemaOptions: { partial: true })
 */
export interface KhovtMasterNhomPartial {
  /** @nullable */
  ghiChu?: string | null;
  /** */
  id?: number;
  /** */
  maNhom?: string;
  /** */
  tenNhom?: string;
}
