/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterVtFilterFieldsOneOf } from './khovtMasterVtFilterFieldsOneOf';
import type { KhovtMasterVtFilterFieldsOneOfTwoItem } from './khovtMasterVtFilterFieldsOneOfTwoItem';

export type KhovtMasterVtFilterFields = KhovtMasterVtFilterFieldsOneOf | KhovtMasterVtFilterFieldsOneOfTwoItem[];
