/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterKhoFilter1FieldsOneOfTwoItem =
  (typeof KhovtMasterKhoFilter1FieldsOneOfTwoItem)[keyof typeof KhovtMasterKhoFilter1FieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterKhoFilter1FieldsOneOfTwoItem = {
  ghiChu: 'ghiChu',
  id: 'id',
  maKho: 'maKho',
  tenKho: 'tenKho',
} as const;
