/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: KhovtTransPhieuXuatWithRelations, schemaOptions: { includeRelations: true })
 */
export interface KhovtTransPhieuXuatWithRelations {
  /** @nullable */
  diDoXuat?: string | null;
  /** @nullable */
  ghiChu?: string | null;
  /** */
  id?: number;
  /** @nullable */
  khoNhap?: string | null;
  /** @nullable */
  khoXuat?: string | null;
  /** @nullable */
  ngayXuat?: string | null;
  /** @nullable */
  nguoiTaoPhieu?: string | null;
  /** @nullable */
  soPhieu?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  thongTinCanhBao?: string | null;
}
