/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterNguonGocFilter1FieldsOneOfTwoItem =
  (typeof KhovtMasterNguonGocFilter1FieldsOneOfTwoItem)[keyof typeof KhovtMasterNguonGocFilter1FieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterNguonGocFilter1FieldsOneOfTwoItem = {
  ghiChu: 'ghiChu',
  id: 'id',
  maNguonGoc: 'maNguonGoc',
  nuocId: 'nuocId',
  tenNhaSx: 'tenNhaSx',
} as const;
