/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterVtFilterFields } from './khovtMasterVtFilterFields';
import type { KhovtMasterVtFilterOrder } from './khovtMasterVtFilterOrder';

export interface KhovtMasterVtFilter {
  fields?: KhovtMasterVtFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterVtFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
