/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNguonGocFilter1FieldsOneOf } from './khovtMasterNguonGocFilter1FieldsOneOf';
import type { KhovtMasterNguonGocFilter1FieldsOneOfTwoItem } from './khovtMasterNguonGocFilter1FieldsOneOfTwoItem';

export type KhovtMasterNguonGocFilter1Fields =
  | KhovtMasterNguonGocFilter1FieldsOneOf
  | KhovtMasterNguonGocFilter1FieldsOneOfTwoItem[];
