/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransThanhKhoanFilter1FieldsOneOf = {
  dvt?: boolean;
  ghiChu?: boolean;
  id?: boolean;
  kiemKe?: boolean;
  kyThanhKhoan?: boolean;
  maVt?: boolean;
  soLo?: boolean;
  tenVt?: boolean;
  tonCuoiKy?: boolean;
  tonDauKy?: boolean;
};
