/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterKhoFilterFieldsOneOf } from './khovtMasterKhoFilterFieldsOneOf';
import type { KhovtMasterKhoFilterFieldsOneOfTwoItem } from './khovtMasterKhoFilterFieldsOneOfTwoItem';

export type KhovtMasterKhoFilterFields = KhovtMasterKhoFilterFieldsOneOf | KhovtMasterKhoFilterFieldsOneOfTwoItem[];
