/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNhomFilterFields } from './khovtMasterNhomFilterFields';
import type { KhovtMasterNhomFilterOrder } from './khovtMasterNhomFilterOrder';

export interface KhovtMasterNhomFilter {
  fields?: KhovtMasterNhomFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterNhomFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
