/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransPhieuNhapFilterFieldsOneOf = {
  donViNhap?: boolean;
  ghiChu?: boolean;
  id?: boolean;
  maKho?: boolean;
  ngayNhanKqtn?: boolean;
  ngayNhap?: boolean;
  nguoiNhap?: boolean;
  soHoaDon?: boolean;
  soPhieuNhap?: boolean;
  typeNhap?: boolean;
  viTriLuuKho?: boolean;
  xeVanChuyen?: boolean;
};
