/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export interface KhovtTransThanhKhoan {
  /** @nullable */
  dvt?: string | null;
  /** @nullable */
  ghiChu?: string | null;
  /** */
  id?: number;
  /** @nullable */
  kiemKe?: number | null;
  /** */
  kyThanhKhoan: string;
  /** @nullable */
  maVt?: string | null;
  /** @nullable */
  soLo?: string | null;
  /** @nullable */
  tenVt?: string | null;
  /** @nullable */
  tonCuoiKy?: number | null;
  /** @nullable */
  tonDauKy?: number | null;
}
