/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterNguonGocFilterFieldsOneOfTwoItem =
  (typeof KhovtMasterNguonGocFilterFieldsOneOfTwoItem)[keyof typeof KhovtMasterNguonGocFilterFieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterNguonGocFilterFieldsOneOfTwoItem = {
  ghiChu: 'ghiChu',
  id: 'id',
  maNguonGoc: 'maNguonGoc',
  nuocId: 'nuocId',
  tenNhaSx: 'tenNhaSx',
} as const;
