/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterKhoFilter1FieldsOneOf } from './khovtMasterKhoFilter1FieldsOneOf';
import type { KhovtMasterKhoFilter1FieldsOneOfTwoItem } from './khovtMasterKhoFilter1FieldsOneOfTwoItem';

export type KhovtMasterKhoFilter1Fields = KhovtMasterKhoFilter1FieldsOneOf | KhovtMasterKhoFilter1FieldsOneOfTwoItem[];
