/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNguonGocFilter1Fields } from './khovtMasterNguonGocFilter1Fields';
import type { KhovtMasterNguonGocFilter1Order } from './khovtMasterNguonGocFilter1Order';
import type { KhovtMasterNguonGocFilter1Where } from './khovtMasterNguonGocFilter1Where';

export interface KhovtMasterNguonGocFilter1 {
  fields?: KhovtMasterNguonGocFilter1Fields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterNguonGocFilter1Order;
  /** @minimum 0 */
  skip?: number;
  where?: KhovtMasterNguonGocFilter1Where;
}
