/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransThanhKhoanFilter1FieldsOneOfTwoItem =
  (typeof KhovtTransThanhKhoanFilter1FieldsOneOfTwoItem)[keyof typeof KhovtTransThanhKhoanFilter1FieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtTransThanhKhoanFilter1FieldsOneOfTwoItem = {
  dvt: 'dvt',
  ghiChu: 'ghiChu',
  id: 'id',
  kiemKe: 'kiemKe',
  kyThanhKhoan: 'kyThanhKhoan',
  maVt: 'maVt',
  soLo: 'soLo',
  tenVt: 'tenVt',
  tonCuoiKy: 'tonCuoiKy',
  tonDauKy: 'tonDauKy',
} as const;
