/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransPhieuNhapFilterFieldsOneOfTwoItem =
  (typeof KhovtTransPhieuNhapFilterFieldsOneOfTwoItem)[keyof typeof KhovtTransPhieuNhapFilterFieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtTransPhieuNhapFilterFieldsOneOfTwoItem = {
  donViNhap: 'donViNhap',
  ghiChu: 'ghiChu',
  id: 'id',
  maKho: 'maKho',
  ngayNhanKqtn: 'ngayNhanKqtn',
  ngayNhap: 'ngayNhap',
  nguoiNhap: 'nguoiNhap',
  soHoaDon: 'soHoaDon',
  soPhieuNhap: 'soPhieuNhap',
  typeNhap: 'typeNhap',
  viTriLuuKho: 'viTriLuuKho',
  xeVanChuyen: 'xeVanChuyen',
} as const;
