/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransThanhKhoanFilter1Fields } from './khovtTransThanhKhoanFilter1Fields';
import type { KhovtTransThanhKhoanFilter1Order } from './khovtTransThanhKhoanFilter1Order';
import type { KhovtTransThanhKhoanFilter1Where } from './khovtTransThanhKhoanFilter1Where';

export interface KhovtTransThanhKhoanFilter1 {
  fields?: KhovtTransThanhKhoanFilter1Fields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtTransThanhKhoanFilter1Order;
  /** @minimum 0 */
  skip?: number;
  where?: KhovtTransThanhKhoanFilter1Where;
}
