/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: KhovtMasterVtWithRelations, schemaOptions: { includeRelations: true })
 */
export interface KhovtMasterVtWithRelations {
  /** */
  dvt: string;
  /** @nullable */
  ghiChu?: string | null;
  /** @nullable */
  maNhom?: string | null;
  /** */
  maVt: string;
  /** */
  tenVt: string;
}
