/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterKhoFilterFieldsOneOfTwoItem =
  (typeof KhovtMasterKhoFilterFieldsOneOfTwoItem)[keyof typeof KhovtMasterKhoFilterFieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterKhoFilterFieldsOneOfTwoItem = {
  ghiChu: 'ghiChu',
  id: 'id',
  maKho: 'maKho',
  tenKho: 'tenKho',
} as const;
