/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransPhieuXuatFilter1FieldsOneOf } from './khovtTransPhieuXuatFilter1FieldsOneOf';
import type { KhovtTransPhieuXuatFilter1FieldsOneOfTwoItem } from './khovtTransPhieuXuatFilter1FieldsOneOfTwoItem';

export type KhovtTransPhieuXuatFilter1Fields =
  | KhovtTransPhieuXuatFilter1FieldsOneOf
  | KhovtTransPhieuXuatFilter1FieldsOneOfTwoItem[];
