/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNhomFilter1FieldsOneOf } from './khovtMasterNhomFilter1FieldsOneOf';
import type { KhovtMasterNhomFilter1FieldsOneOfTwoItem } from './khovtMasterNhomFilter1FieldsOneOfTwoItem';

export type KhovtMasterNhomFilter1Fields =
  | KhovtMasterNhomFilter1FieldsOneOf
  | KhovtMasterNhomFilter1FieldsOneOfTwoItem[];
