/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNhomFilter1Fields } from './khovtMasterNhomFilter1Fields';
import type { KhovtMasterNhomFilter1Order } from './khovtMasterNhomFilter1Order';
import type { KhovtMasterNhomFilter1Where } from './khovtMasterNhomFilter1Where';

export interface KhovtMasterNhomFilter1 {
  fields?: KhovtMasterNhomFilter1Fields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterNhomFilter1Order;
  /** @minimum 0 */
  skip?: number;
  where?: KhovtMasterNhomFilter1Where;
}
