/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransPhieuXuatFilterFields } from './khovtTransPhieuXuatFilterFields';
import type { KhovtTransPhieuXuatFilterOrder } from './khovtTransPhieuXuatFilterOrder';

export interface KhovtTransPhieuXuatFilter {
  fields?: KhovtTransPhieuXuatFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtTransPhieuXuatFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
