/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterVtFilter1Fields } from './khovtMasterVtFilter1Fields';
import type { KhovtMasterVtFilter1Order } from './khovtMasterVtFilter1Order';
import type { KhovtMasterVtFilter1Where } from './khovtMasterVtFilter1Where';

export interface KhovtMasterVtFilter1 {
  fields?: KhovtMasterVtFilter1Fields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterVtFilter1Order;
  /** @minimum 0 */
  skip?: number;
  where?: KhovtMasterVtFilter1Where;
}
