/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Partial<KhovtMasterNguonGoc>, schemaOptions: { partial: true })
 */
export interface KhovtMasterNguonGocPartial {
  /** @nullable */
  ghiChu?: string | null;
  /** */
  id?: number;
  /** */
  maNguonGoc?: string;
  /** */
  nuocId?: number;
  /** */
  tenNhaSx?: string;
}
