/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export interface KhovtMasterKho {
  /** @nullable */
  ghiChu?: string | null;
  /** */
  id?: number;
  /** */
  maKho: string;
  /** */
  tenKho: string;
}
