/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterKhoFilter1 } from './khovtMasterKhoFilter1';

export type KhovtMasterKhoControllerFindParams = {
  filter?: KhovtMasterKhoFilter1;
};
