/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransPhieuNhapFilterFields } from './khovtTransPhieuNhapFilterFields';
import type { KhovtTransPhieuNhapFilterOrder } from './khovtTransPhieuNhapFilterOrder';

export interface KhovtTransPhieuNhapFilter {
  fields?: KhovtTransPhieuNhapFilterFields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtTransPhieuNhapFilterOrder;
  /** @minimum 0 */
  skip?: number;
}
