/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtTransPhieuNhapFilter1FieldsOneOf } from './khovtTransPhieuNhapFilter1FieldsOneOf';
import type { KhovtTransPhieuNhapFilter1FieldsOneOfTwoItem } from './khovtTransPhieuNhapFilter1FieldsOneOfTwoItem';

export type KhovtTransPhieuNhapFilter1Fields =
  | KhovtTransPhieuNhapFilter1FieldsOneOf
  | KhovtTransPhieuNhapFilter1FieldsOneOfTwoItem[];
