/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterNhomFilterFieldsOneOfTwoItem =
  (typeof KhovtMasterNhomFilterFieldsOneOfTwoItem)[keyof typeof KhovtMasterNhomFilterFieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtMasterNhomFilterFieldsOneOfTwoItem = {
  ghiChu: 'ghiChu',
  id: 'id',
  maNhom: 'maNhom',
  tenNhom: 'tenNhom',
} as const;
