/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterNhomFilterFieldsOneOf } from './khovtMasterNhomFilterFieldsOneOf';
import type { KhovtMasterNhomFilterFieldsOneOfTwoItem } from './khovtMasterNhomFilterFieldsOneOfTwoItem';

export type KhovtMasterNhomFilterFields = KhovtMasterNhomFilterFieldsOneOf | KhovtMasterNhomFilterFieldsOneOfTwoItem[];
