/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransPhieuXuatFilterFieldsOneOfTwoItem =
  (typeof KhovtTransPhieuXuatFilterFieldsOneOfTwoItem)[keyof typeof KhovtTransPhieuXuatFilterFieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtTransPhieuXuatFilterFieldsOneOfTwoItem = {
  diDoXuat: 'diDoXuat',
  ghiChu: 'ghiChu',
  id: 'id',
  khoNhap: 'khoNhap',
  khoXuat: 'khoXuat',
  ngayXuat: 'ngayXuat',
  nguoiTaoPhieu: 'nguoiTaoPhieu',
  soPhieu: 'soPhieu',
  status: 'status',
  thongTinCanhBao: 'thongTinCanhBao',
} as const;
