/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtMasterNguonGocFilter1FieldsOneOf = {
  ghiChu?: boolean;
  id?: boolean;
  maNguonGoc?: boolean;
  nuocId?: boolean;
  tenNhaSx?: boolean;
};
