/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { KhovtMasterKhoFilter1Fields } from './khovtMasterKhoFilter1Fields';
import type { KhovtMasterKhoFilter1Order } from './khovtMasterKhoFilter1Order';
import type { KhovtMasterKhoFilter1Where } from './khovtMasterKhoFilter1Where';

export interface KhovtMasterKhoFilter1 {
  fields?: KhovtMasterKhoFilter1Fields;
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
  order?: KhovtMasterKhoFilter1Order;
  /** @minimum 0 */
  skip?: number;
  where?: KhovtMasterKhoFilter1Where;
}
