/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

export type KhovtTransThanhKhoanFilterFieldsOneOfTwoItem =
  (typeof KhovtTransThanhKhoanFilterFieldsOneOfTwoItem)[keyof typeof KhovtTransThanhKhoanFilterFieldsOneOfTwoItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KhovtTransThanhKhoanFilterFieldsOneOfTwoItem = {
  dvt: 'dvt',
  ghiChu: 'ghiChu',
  id: 'id',
  kiemKe: 'kiemKe',
  kyThanhKhoan: 'kyThanhKhoan',
  maVt: 'maVt',
  soLo: 'soLo',
  tenVt: 'tenVt',
  tonCuoiKy: 'tonCuoiKy',
  tonDauKy: 'tonDauKy',
} as const;
