/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Omit<KhovtMasterNguonGoc, 'id'>, schemaOptions: { title: 'NewKhovtMasterNguonGoc', exclude: [ 'id' ] })
 */
export interface NewKhovtMasterNguonGoc {
  /** @nullable */
  ghiChu?: string | null;
  /** */
  maNguonGoc: string;
  /** */
  nuocId: number;
  /** */
  tenNhaSx: string;
}
