/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Omit<KhovtTransThanhKhoan, 'id'>, schemaOptions: { title: 'NewKhovtTransThanhKhoan', exclude: [ 'id' ] })
 */
export interface NewKhovtTransThanhKhoan {
  /** @nullable */
  dvt?: string | null;
  /** @nullable */
  ghiChu?: string | null;
  /** @nullable */
  kiemKe?: number | null;
  /** */
  kyThanhKhoan: string;
  /** @nullable */
  maVt?: string | null;
  /** @nullable */
  soLo?: string | null;
  /** @nullable */
  tenVt?: string | null;
  /** @nullable */
  tonCuoiKy?: number | null;
  /** @nullable */
  tonDauKy?: number | null;
}
