/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Omit<KhovtTransPhieuXuat, 'id'>, schemaOptions: { title: 'NewKhovtTransPhieuXuat', exclude: [ 'id' ] })
 */
export interface NewKhovtTransPhieuXuat {
  /** @nullable */
  diDoXuat?: string | null;
  /** @nullable */
  ghiChu?: string | null;
  /** @nullable */
  khoNhap?: string | null;
  /** @nullable */
  khoXuat?: string | null;
  /** @nullable */
  ngayXuat?: string | null;
  /** @nullable */
  nguoiTaoPhieu?: string | null;
  /** @nullable */
  soPhieu?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  thongTinCanhBao?: string | null;
}
