/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Omit<KhovtMasterKho, 'id'>, schemaOptions: { title: 'NewKhovtMasterKho', exclude: [ 'id' ] })
 */
export interface NewKhovtMasterKho {
  /** @nullable */
  ghiChu?: string | null;
  /** */
  maKho: string;
  /** */
  tenKho: string;
}
