/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */

/**
 * (tsType: Omit<KhovtMasterNhom, 'id'>, schemaOptions: { title: 'NewKhovtMasterNhom', exclude: [ 'id' ] })
 */
export interface NewKhovtMasterNhom {
  /** @nullable */
  ghiChu?: string | null;
  /** */
  maNhom: string;
  /** */
  tenNhom: string;
}
