/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * pkh-api
 * pkh api
 * OpenAPI spec version: 0.0.1
 */
import type { PingResponseHeaders } from './pingResponseHeaders';

export interface PingResponse {
  date?: string;
  greeting?: string;
  headers?: PingResponseHeaders;
  url?: string;
}
